In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [4]:
import numpy as np

In [5]:
import matplotlib.pyplot as plt

In [6]:
s=pd.Series(range(0,4))

In [7]:
s

0    0
1    1
2    2
3    3
dtype: int64

In [8]:
s1=pd.Series(range(1,5))

In [9]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [10]:
s+s1

0    1
1    3
2    5
3    7
dtype: int64

In [11]:
s1+s

0    1
1    3
2    5
3    7
dtype: int64

In [12]:
s2=pd.Series([1,2,3,4],index=[3,2,1,0])

In [13]:
s2

3    1
2    2
1    3
0    4
dtype: int64

In [14]:
s1+s2

0    5
1    5
2    5
3    5
dtype: int64

In [15]:
df=pd.DataFrame()

In [16]:
df

Empty DataFrame
Columns: []
Index: []

In [23]:
# df=pd.read_csv('file.csv',header=0,index_col=0,quotechar='"',sep=',',na_values=['na','-','.',''])

In [19]:
from io import StringIO

In [20]:
data=""",Animal,Cuteness,Desirable
A,    dog,   8.7,        True
B,   cat,   9.5,        False"""

In [21]:
df=pd.read_csv(StringIO(data))

In [22]:
df

  Unnamed: 0   Animal  Cuteness      Desirable
0          A      dog       8.7           True
1          B      cat       9.5          False

In [37]:
df=pd.read_csv(StringIO(data),header=0,index_col=0,skipinitialspace=False)

In [38]:
df

    Animal  Cuteness      Desirable
A      dog       8.7           True
B      cat       9.5          False

In [24]:
df=pd.read_csv(StringIO(data),header=0,index_col=0,skipinitialspace=True)

In [25]:
df

  Animal  Cuteness  Desirable
A    dog       8.7       True
B    cat       9.5      False

In [26]:
df=pd.read_clipboard()

In [27]:
df

                         My    Pandas Project
This repo contains  Jupyter  Notebook  files.

In [28]:
df

                         My    Pandas Project
This repo contains  Jupyter  Notebook  files.

In [31]:
#df=pd.read_html(url/html_string)
#df=pd.read_excel("file.xlsx")
#df=pd.read_json(path/JSon string)
#df=pd.read_csv("file.csv")
#df=pd.read_sql(query,connection)

In [32]:
df=pd.DataFrame(np.random.rand(1100,6))

In [33]:
df

             0         1         2         3         4         5
0     0.818558  0.245590  0.650658  0.258397  0.465862  0.300330
1     0.933507  0.211731  0.418153  0.082763  0.626028  0.983234
2     0.904163  0.258865  0.560836  0.981620  0.285833  0.710245
3     0.543425  0.410930  0.826177  0.050626  0.212352  0.021447
4     0.376472  0.289608  0.548770  0.311195  0.670152  0.793573
...        ...       ...       ...       ...       ...       ...
1095  0.535870  0.105600  0.087786  0.650808  0.451560  0.457249
1096  0.640357  0.958793  0.201626  0.447778  0.886456  0.284640
1097  0.148653  0.107912  0.516859  0.104816  0.102254  0.979788
1098  0.170795  0.522528  0.577428  0.164605  0.613678  0.609819
1099  0.592975  0.070298  0.569241  0.335557  0.482500  0.681295

[1100 rows x 6 columns]

In [34]:
df=pd.DataFrame(np.random.rand(1100,6),columns=list("ABCDEF"))

In [35]:
df

             A         B         C         D         E         F
0     0.033303  0.513008  0.410372  0.841771  0.263254  0.318341
1     0.230666  0.731471  0.207427  0.600406  0.551345  0.955644
2     0.411931  0.114693  0.819482  0.491029  0.054790  0.479296
3     0.732770  0.900753  0.591547  0.032976  0.568797  0.382148
4     0.958051  0.410952  0.240200  0.796893  0.860985  0.825408
...        ...       ...       ...       ...       ...       ...
1095  0.805202  0.702879  0.706737  0.624162  0.164881  0.335045
1096  0.246344  0.147623  0.996246  0.090057  0.071167  0.488715
1097  0.169797  0.633655  0.017013  0.532223  0.021239  0.938522
1098  0.581643  0.215741  0.010702  0.533306  0.533905  0.282330
1099  0.048037  0.300926  0.733085  0.654173  0.377686  0.815750

[1100 rows x 6 columns]

In [36]:
df=pd.DataFrame(np.random.rand(10,6),columns=list("ABCDEF"))-0.5

In [37]:
df

          A         B         C         D         E         F
0 -0.287723  0.456970 -0.072529  0.323051 -0.264933  0.464342
1  0.163620 -0.000830  0.039201  0.085908  0.231388  0.463509
2 -0.419882  0.404805 -0.145288 -0.236905  0.246294 -0.053126
3  0.406420 -0.272393 -0.239509  0.337533  0.001038 -0.196952
4  0.226759 -0.344163  0.089391  0.085634  0.498934 -0.370244
5  0.102660 -0.041247  0.488090 -0.111873  0.485037 -0.463147
6 -0.437586  0.099031  0.344018  0.485398  0.171750  0.120703
7 -0.431302 -0.089889 -0.228589  0.124140  0.090596 -0.389445
8  0.290009  0.139949 -0.356864  0.459284 -0.435971 -0.378484
9  0.317536  0.215564  0.384119  0.102630  0.329925 -0.469103

In [38]:
df=(pd.DataFrame(np.random.rand(1100,6),columns=list("ABCDEF"))-0.5).cumsum()

In [39]:
df

             A         B          C         D          E          F
0     0.213916  0.409559   0.138767 -0.102868  -0.403552   0.122212
1     0.054282  0.604569  -0.294632  0.076313   0.033843   0.487206
2     0.176888  0.656471  -0.156687  0.187052  -0.098320   0.317106
3     0.374276  0.320158  -0.255140  0.648093   0.305393   0.639353
4     0.152975  0.493102  -0.384132  0.193687   0.599725   0.859255
...        ...       ...        ...       ...        ...        ...
1095 -1.536301  5.381084  10.236023 -0.022521 -13.546043 -13.314365
1096 -2.026894  5.132343  10.147963 -0.396686 -13.379561 -13.088909
1097 -2.279364  5.310519  10.510523 -0.225688 -12.959585 -12.924298
1098 -1.878349  5.776012  10.056090  0.110210 -12.835673 -13.039006
1099 -1.508355  5.388614   9.756062 -0.130268 -12.446635 -12.969998

[1100 rows x 6 columns]

In [40]:
df=pd.DataFrame(np.random.rand(10,6),columns=list("ABCDEF"))

In [41]:
df

          A         B         C         D         E         F
0  0.447798  0.106174  0.847656  0.013513  0.237708  0.418384
1  0.664443  0.640184  0.678110  0.160539  0.447030  0.717794
2  0.796843  0.941733  0.390315  0.027814  0.427677  0.363840
3  0.746367  0.040361  0.258370  0.160704  0.876003  0.836757
4  0.792152  0.581581  0.595262  0.500837  0.092783  0.541571
5  0.100490  0.172705  0.081481  0.398447  0.406592  0.025251
6  0.893683  0.463058  0.995750  0.126693  0.881386  0.074138
7  0.673436  0.045294  0.384898  0.287288  0.801524  0.815192
8  0.098064  0.367517  0.757866  0.328985  0.693027  0.010438
9  0.878153  0.770188  0.873727  0.219373  0.913889  0.891162

In [42]:
df=pd.DataFrame(np.random.rand(10,5),columns=list("ABCDE")).cumsum()

In [43]:
df

          A         B         C         D         E
0  0.671763  0.295964  0.436789  0.886549  0.013376
1  0.817334  1.003759  0.663527  1.878779  0.738570
2  1.540605  1.920118  0.853165  2.616040  1.547922
3  2.109886  2.687321  1.795762  2.845932  2.346024
4  2.304832  3.628923  2.039995  3.005773  2.404754
5  3.071601  3.965488  2.982195  3.820097  2.778852
6  3.291637  4.840162  3.098496  4.520573  3.281651
7  3.784042  5.168741  3.638133  5.021877  3.889423
8  4.261386  5.497999  3.816367  5.219116  4.172691
9  4.456765  6.319301  4.706287  5.280427  4.935128

In [44]:
d=df.to_dict()

In [45]:
d

{'A': {0: 0.6717631448659733,
  1: 0.8173339869813029,
  2: 1.540604547628217,
  3: 2.1098858389766666,
  4: 2.30483198968409,
  5: 3.0716014378613328,
  6: 3.2916371959764077,
  7: 3.784041573703843,
  8: 4.261385580300708,
  9: 4.456765484925838},
 'B': {0: 0.2959642243464625,
  1: 1.0037592843674004,
  2: 1.9201184147908745,
  3: 2.6873214355541974,
  4: 3.628923455879911,
  5: 3.965487603069882,
  6: 4.840161561323689,
  7: 5.1687406158473,
  8: 5.497998570053406,
  9: 6.319301273865879},
 'C': {0: 0.43678861604247887,
  1: 0.6635272194163931,
  2: 0.8531645911860347,
  3: 1.7957621555989345,
  4: 2.0399950396019793,
  5: 2.9821954611892583,
  6: 3.09849603214371,
  7: 3.638132925823395,
  8: 3.8163669202262405,
  9: 4.706286717056223},
 'D': {0: 0.8865490244448965,
  1: 1.8787792353811097,
  2: 2.6160401027142504,
  3: 2.8459315209718477,
  4: 3.005772572593668,
  5: 3.820097426941878,
  6: 4.520573334005356,
  7: 5.021877488872842,
  8: 5.219116038534982,
  9: 5.280426961294873},
 'E': {0: 0.013375888767556687,
  1: 0.738570077829679,
  2: 1.547921993155672,
  3: 2.3460236060181145,
  4: 2.404753782776889,
  5: 2.7788520247380095,
  6: 3.281650783679346,
  7: 3.889423448137742,
  8: 4.172691190479295,
  9: 4.935128161875872}}

In [46]:
m=d.keys()

In [47]:
m

dict_keys(['A', 'B', 'C', 'D', 'E'])

In [48]:
html=df.to_html()

In [49]:
html

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>A</th>\n      <th>B</th>\n      <th>C</th>\n      <th>D</th>\n      <th>E</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.671763</td>\n      <td>0.295964</td>\n      <td>0.436789</td>\n      <td>0.886549</td>\n      <td>0.013376</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>0.817334</td>\n      <td>1.003759</td>\n      <td>0.663527</td>\n      <td>1.878779</td>\n      <td>0.738570</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1.540605</td>\n      <td>1.920118</td>\n      <td>0.853165</td>\n      <td>2.616040</td>\n      <td>1.547922</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2.109886</td>\n      <td>2.687321</td>\n      <td>1.795762</td>\n      <td>2.845932</td>\n      <td>2.346024</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2.304832</td>\n      <td>3.628923</td>\n      <td>2.039995</td>\n      <td>3.005773</td>\n      <td>2.404754</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>3.071601</td>\n      <td>3.965488</td>\n      <td>2.982195</td>\n      <td>3.820097</td>\n      <td>2.778852</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>3.291637</td>\n      <td>4.840162</td>\n      <td>3.098496</td>\n      <td>4.520573</td>\n      <td>3.281651</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>3.784042</td>\n      <td>5.168741</td>\n      <td>3.638133</td>\n      <td>5.021877</td>\n      <td>3.889423</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>4.261386</td>\n      <td>5.497999</td>\n      <td>3.816367</td>\n      <td>5.219116</td>\n      <td>4.172691</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>4.456765</td>\n      <td>6.319301</td>\n      <td>4.706287</td>\n      <td>5.280427</td>\n      <td>4.935128</td>\n    </tr>\n  </tbody>\n</table>'

In [50]:
import pandas as pd
market1={
    "veg":["tomato","potato","carrot","beetroot","chilli"],
    "unit":[3,2,1,1,2],
    "colour":["red","brown","orange","pink","green"],
    "max_price":[40,50,60,60,70],
    "min_price":[20,40,40,40,30]
}

In [51]:
d=pd.Series(market1)

In [52]:
d

veg          [tomato, potato, carrot, beetroot, chilli]
unit                                    [3, 2, 1, 1, 2]
colour                [red, brown, orange, pink, green]
max_price                          [40, 50, 60, 60, 70]
min_price                          [20, 40, 40, 40, 30]
dtype: object

In [53]:
d=pd.DataFrame(market1)

In [54]:
d

        veg  unit  colour  max_price  min_price
0    tomato     3     red         40         20
1    potato     2   brown         50         40
2    carrot     1  orange         60         40
3  beetroot     1    pink         60         40
4    chilli     2   green         70         30

In [55]:
d.describe()

          unit  max_price  min_price
count  5.00000   5.000000   5.000000
mean   1.80000  56.000000  34.000000
std    0.83666  11.401754   8.944272
min    1.00000  40.000000  20.000000
25%    1.00000  50.000000  30.000000
50%    2.00000  60.000000  40.000000
75%    2.00000  60.000000  40.000000
max    3.00000  70.000000  40.000000

In [56]:
d.describe(include="all")

           veg     unit colour  max_price  min_price
count        5  5.00000      5   5.000000   5.000000
unique       5      NaN      5        NaN        NaN
top     tomato      NaN    red        NaN        NaN
freq         1      NaN      1        NaN        NaN
mean       NaN  1.80000    NaN  56.000000  34.000000
std        NaN  0.83666    NaN  11.401754   8.944272
min        NaN  1.00000    NaN  40.000000  20.000000
25%        NaN  1.00000    NaN  50.000000  30.000000
50%        NaN  2.00000    NaN  60.000000  40.000000
75%        NaN  2.00000    NaN  60.000000  40.000000
max        NaN  3.00000    NaN  70.000000  40.000000

In [57]:
d.iloc[:4]

        veg  unit  colour  max_price  min_price
0    tomato     3     red         40         20
1    potato     2   brown         50         40
2    carrot     1  orange         60         40
3  beetroot     1    pink         60         40

In [58]:
d.iloc[:5,:5]

        veg  unit  colour  max_price  min_price
0    tomato     3     red         40         20
1    potato     2   brown         50         40
2    carrot     1  orange         60         40
3  beetroot     1    pink         60         40
4    chilli     2   green         70         30

In [59]:
d.loc[4]

veg          chilli
unit              2
colour        green
max_price        70
min_price        30
Name: 4, dtype: object

In [61]:
d=pd.Series(market1)

In [62]:
d

veg          [tomato, potato, carrot, beetroot, chilli]
unit                                    [3, 2, 1, 1, 2]
colour                [red, brown, orange, pink, green]
max_price                          [40, 50, 60, 60, 70]
min_price                          [20, 40, 40, 40, 30]
dtype: object

In [63]:
d.dtypes

dtype('O')

In [64]:
d.T

veg          [tomato, potato, carrot, beetroot, chilli]
unit                                    [3, 2, 1, 1, 2]
colour                [red, brown, orange, pink, green]
max_price                          [40, 50, 60, 60, 70]
min_price                          [20, 40, 40, 40, 30]
dtype: object

In [65]:
d=pd.DataFrame(market1)

In [66]:
d

        veg  unit  colour  max_price  min_price
0    tomato     3     red         40         20
1    potato     2   brown         50         40
2    carrot     1  orange         60         40
3  beetroot     1    pink         60         40
4    chilli     2   green         70         30

In [67]:
transpose=d.T

In [68]:
transpose

                0       1       2         3       4
veg        tomato  potato  carrot  beetroot  chilli
unit            3       2       1         1       2
colour        red   brown  orange      pink   green
max_price      40      50      60        60      70
min_price      20      40      40        40      30

In [69]:
d

        veg  unit  colour  max_price  min_price
0    tomato     3     red         40         20
1    potato     2   brown         50         40
2    carrot     1  orange         60         40
3  beetroot     1    pink         60         40
4    chilli     2   green         70         30

In [70]:
d.axes

[RangeIndex(start=0, stop=5, step=1),
 Index(['veg', 'unit', 'colour', 'max_price', 'min_price'], dtype='object')]

In [71]:
(ri,ci)=d.axes

In [72]:
(ri,ci)

(RangeIndex(start=0, stop=5, step=1),
 Index(['veg', 'unit', 'colour', 'max_price', 'min_price'], dtype='object'))

In [73]:
d.dtypes

veg          object
unit          int64
colour       object
max_price     int64
min_price     int64
dtype: object

In [74]:
d.ndim

2

In [75]:
d.shape

(5, 5)

In [76]:
d.size

25

In [77]:
d.values

array([['tomato', 3, 'red', 40, 20],
       ['potato', 2, 'brown', 50, 40],
       ['carrot', 1, 'orange', 60, 40],
       ['beetroot', 1, 'pink', 60, 40],
       ['chilli', 2, 'green', 70, 30]], dtype=object)

In [78]:
d.copy()

        veg  unit  colour  max_price  min_price
0    tomato     3     red         40         20
1    potato     2   brown         50         40
2    carrot     1  orange         60         40
3  beetroot     1    pink         60         40
4    chilli     2   green         70         30

In [79]:
d.sort_index(axis=0)

        veg  unit  colour  max_price  min_price
0    tomato     3     red         40         20
1    potato     2   brown         50         40
2    carrot     1  orange         60         40
3  beetroot     1    pink         60         40
4    chilli     2   green         70         30

In [80]:
d.sort_index(axis=1)

   colour  max_price  min_price  unit       veg
0     red         40         20     3    tomato
1   brown         50         40     2    potato
2  orange         60         40     1    carrot
3    pink         60         40     1  beetroot
4   green         70         30     2    chilli

In [81]:
d.iterrows()

In [82]:
d.cumsum()

,veg,unit,colour,max_price,min_price
0,tomato,3,red,40,20
1,tomatopotato,5,redbrown,90,60
2,tomatopotatocarrot,6,redbrownorange,150,100
3,tomatopotatocarrotbeetroot,7,redbrownorangepink,210,140
4,tomatopotatocarrotbeetrootchilli,9,redbrownorangepinkgreen,280,170

In [83]:
d.cummin()

        veg  unit colour  max_price  min_price
0    tomato     3    red         40         20
1    potato     2  brown         40         20
2    carrot     1  brown         40         20
3  beetroot     1  brown         40         20
4  beetroot     1  brown         40         20

In [84]:
d.cummax()

      veg  unit colour  max_price  min_price
0  tomato     3    red         40         20
1  tomato     3    red         50         40
2  tomato     3    red         60         40
3  tomato     3    red         60         40
4  tomato     3    red         70         40

In [85]:
d.min()

veg          beetroot
unit                1
colour          brown
max_price          40
min_price          20
dtype: object

In [86]:
d.sum()

veg          tomatopotatocarrotbeetrootchilli
unit                                        9
colour                redbrownorangepinkgreen
max_price                                 280
min_price                                 170
dtype: object

In [87]:
d['unit'].median()

2.0

In [88]:
d.count()

veg          5
unit         5
colour       5
max_price    5
min_price    5
dtype: int64

In [89]:
d.columns

Index(['veg', 'unit', 'colour', 'max_price', 'min_price'], dtype='object')

In [90]:

d.head(1)

      veg  unit colour  max_price  min_price
0  tomato     3    red         40         20

In [91]:
d['unit'].head(1)

0    3
Name: unit, dtype: int64

In [92]:
d.columns.values

array(['veg', 'unit', 'colour', 'max_price', 'min_price'], dtype=object)

In [93]:
d.columns.tolist()

['veg', 'unit', 'colour', 'max_price', 'min_price']

In [95]:
d.columns

Index(['veg', 'unit', 'colour', 'max_price', 'min_price'], dtype='object')

In [96]:
d.rename(columns={"veg":"veges"})

      veges  unit  colour  max_price  min_price
0    tomato     3     red         40         20
1    potato     2   brown         50         40
2    carrot     1  orange         60         40
3  beetroot     1    pink         60         40
4    chilli     2   green         70         30

In [97]:
d.columns

Index(['veg', 'unit', 'colour', 'max_price', 'min_price'], dtype='object')

In [98]:
d.columns[2]

'colour'

In [99]:
d['unit']

0    3
1    2
2    1
3    1
4    2
Name: unit, dtype: int64

In [100]:
d[['unit']]

   unit
0     3
1     2
2     1
3     1
4     2