In [2]:
print(10)

10

# import lib

In [5]:
import pandas as pd
print(pd.__version__)

2.3.3

In [6]:
veges=['beetroot','carror','tomato','potato']

In [7]:
pd.Series(veges)

0    beetroot
1      carror
2      tomato
3      potato
dtype: object

In [7]:
print(type(veges))

<class 'list'>

In [8]:
veges_series=pd.Series(veges)

In [9]:
print(type(veges_series))

<class 'pandas.core.series.Series'>

In [10]:
veg_series=pd.Series(veges,index=["a","b","c","d"])

In [11]:
veg_series

a    beetroot
b      carror
c      tomato
d      potato
dtype: object

In [13]:
veg_series['a']

'beetroot'

In [15]:
veg_series.drop(['b'])

a    beetroot
c      tomato
d      potato
dtype: object

In [16]:
market1={
    "veg":["tomato","potato","carrot","beetroot","chilli"],
    "unit":[3,2,1,1,2],
    "colour":["red","brown","orange","purple","green"],
    "max_price":[40,50,60,60,70],
    "min_price":[20,40,40,40,30]
}

In [17]:
market1

{'veg': ['tomato', 'potato', 'carrot', 'beetroot', 'chilli'],
 'unit': [3, 2, 1, 1, 2],
 'colour': ['red', 'brown', 'orange', 'purple', 'green'],
 'max_price': [40, 50, 60, 60, 70],
 'min_price': [20, 40, 40, 40, 30]}

In [18]:
market=pd.DataFrame(market1)

In [19]:
market

        veg  unit  colour  max_price  min_price
0    tomato     3     red         40         20
1    potato     2   brown         50         40
2    carrot     1  orange         60         40
3  beetroot     1  purple         60         40
4    chilli     2   green         70         30

In [23]:
market.loc[4]

veg          chilli
unit              2
colour        green
max_price        70
min_price        30
Name: 4, dtype: object

In [24]:
market.iloc[1:3]

      veg  unit  colour  max_price  min_price
1  potato     2   brown         50         40
2  carrot     1  orange         60         40

In [30]:
market.iloc[1:5,0:5]

        veg  unit  colour  max_price  min_price
1    potato     2   brown         50         40
2    carrot     1  orange         60         40
3  beetroot     1  purple         60         40
4    chilli     2   green         70         30

In [32]:
market['max_price'].sum()

np.int64(280)

In [40]:
data={'veg':['beetroot', 'carrot', 'tomato', 'kovakkai','coconut'],
      'color' : ['purple', 'orange','red','green','white'],
      'unit':['1kg','1kg','1kg','1kg','1piece'],
      'min':[15,25,53,30,'seventeen'],
      'max':[40,45,90,45,38],
     }

In [43]:
market1=pd.DataFrame(data)

In [44]:
market1

        veg   color    unit        min  max
0  beetroot  purple     1kg         15   40
1    carrot  orange     1kg         25   45
2    tomato     red     1kg         53   90
3  kovakkai   green     1kg         30   45
4   coconut   white  1piece  seventeen   38

In [36]:
market1.isna()

   vegetables  color   unit    min    max
0       False  False  False  False  False
1       False  False  False  False  False
2       False  False  False  False  False
3       False  False  False  False  False
4       False  False  False  False  False

In [37]:
market1.isna().sum()

vegetables    0
color         0
unit          0
min           0
max           0
dtype: int64

In [51]:
pd.merge(market,market1,  how='cross')

,veg_x,unit_x,colour,max_price,min_price,veg_y,color,unit_y,min,max
0,tomato,3,red,40,20,beetroot,purple,1kg,15,40
1,tomato,3,red,40,20,carrot,orange,1kg,25,45
2,tomato,3,red,40,20,tomato,red,1kg,53,90
3,tomato,3,red,40,20,kovakkai,green,1kg,30,45
4,tomato,3,red,40,20,coconut,white,1piece,seventeen,38
5,potato,2,brown,50,40,beetroot,purple,1kg,15,40
6,potato,2,brown,50,40,carrot,orange,1kg,25,45
7,potato,2,brown,50,40,tomato,red,1kg,53,90
8,potato,2,brown,50,40,kovakkai,green,1kg,30,45
9,potato,2,brown,50,40,coconut,white,1piece,seventeen,38
10,carrot,1,orange,60,40,beetroot,purple,1kg,15,40
11,carrot,1,orange,60,40,carrot,orange,1kg,25,45
12,carrot,1,orange,60,40,tomato,red,1kg,53,90
13,carrot,1,orange,60,40,kovakkai,green,1kg,30,45
14,carrot,1,orange,60,40,coconut,white,1piece,seventeen,38
15,beetroot,1,purple,60,40,beetroot,purple,1kg,15,40
16,beetroot,1,purple,60,40,carrot,orange,1kg,25,45
17,beetroot,1,purple,60,40,tomato,red,1kg,53,90
18,beetroot,1,purple,60,40,kovakkai,green,1kg,30,45
19,beetroot,1,purple,60,40,coconut,white,1piece,seventeen,38
20,chilli,2,green,70,30,beetroot,purple,1kg,15,40
21,chilli,2,green,70,30,carrot,orange,1kg,25,45
22,chilli,2,green,70,30,tomato,red,1kg,53,90
23,chilli,2,green,70,30,kovakkai,green,1kg,30,45
24,chilli,2,green,70,30,coconut,white,1piece,seventeen,38

In [52]:
market.describe()

          unit  max_price  min_price
count  5.00000   5.000000   5.000000
mean   1.80000  56.000000  34.000000
std    0.83666  11.401754   8.944272
min    1.00000  40.000000  20.000000
25%    1.00000  50.000000  30.000000
50%    2.00000  60.000000  40.000000
75%    2.00000  60.000000  40.000000
max    3.00000  70.000000  40.000000

In [53]:
market1['max'].mean()

np.float64(51.6)

In [54]:
market1['max'].mode()

0    45
Name: max, dtype: int64

In [55]:
market1['max'].median()

45.0

In [56]:
market.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   veg        5 non-null      object
 1   unit       5 non-null      int64
 2   colour     5 non-null      object
 3   max_price  5 non-null      int64
 4   min_price  5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

In [58]:
pd.concat([market,market1])

        veg    unit  colour  max_price  min_price   color        min   max
0    tomato       3     red       40.0       20.0     NaN        NaN   NaN
1    potato       2   brown       50.0       40.0     NaN        NaN   NaN
2    carrot       1  orange       60.0       40.0     NaN        NaN   NaN
3  beetroot       1  purple       60.0       40.0     NaN        NaN   NaN
4    chilli       2   green       70.0       30.0     NaN        NaN   NaN
0  beetroot     1kg     NaN        NaN        NaN  purple         15  40.0
1    carrot     1kg     NaN        NaN        NaN  orange         25  45.0
2    tomato     1kg     NaN        NaN        NaN     red         53  90.0
3  kovakkai     1kg     NaN        NaN        NaN   green         30  45.0
4   coconut  1piece     NaN        NaN        NaN   white  seventeen  38.0

In [59]:
pd.concat([market,market1],axis=1)

,veg,unit,colour,max_price,min_price,veg,color,unit,min,max
0,tomato,3,red,40,20,beetroot,purple,1kg,15,40
1,potato,2,brown,50,40,carrot,orange,1kg,25,45
2,carrot,1,orange,60,40,tomato,red,1kg,53,90
3,beetroot,1,purple,60,40,kovakkai,green,1kg,30,45
4,chilli,2,green,70,30,coconut,white,1piece,seventeen,38

In [60]:
market

        veg  unit  colour  max_price  min_price
0    tomato     3     red         40         20
1    potato     2   brown         50         40
2    carrot     1  orange         60         40
3  beetroot     1  purple         60         40
4    chilli     2   green         70         30

In [61]:
market.loc[4,'max_price']=pd.nan

AttributeError: module 'pandas' has no attribute 'nan'

In [64]:
market.loc[4]

veg          chilli
unit              2
colour        green
max_price        70
min_price        30
Name: 4, dtype: object

In [65]:
market.iloc[0:3]

      veg  unit  colour  max_price  min_price
0  tomato     3     red         40         20
1  potato     2   brown         50         40
2  carrot     1  orange         60         40